kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sandbox-80-frontend
  namespace: sandbox
spec:
  podSelector: 
    matchLabels:
      tier: frontend

  ingress:
  - ports:
    - port: 80
    from: []
