apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: conference
    app.kubernetes.io/part-of: tk-apps
  name: conference
  namespace: scratch
spec:
  replicas: 3
  selector:
    matchLabels:
      run: conference
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: conference
        app.kubernetes.io/part-of: tk-apps
    spec:
      containers:
      - image: tkrausjr/conference-app
        imagePullPolicy: Always
        name: conference-app
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
