apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: conference-app
  name: conference-app
  namespace: dev-webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      run: conference-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: conference-app
    spec:
      containers:
      # - image: unsafe-registry.somewhere.com/proxy/tkrausjr/conference-app
      - image: harbor.mbentley.net/docker.io/tkrausjr/conference-app
        name: conference-app
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: conference-app
  name: conference-app
  namespace: dev-webapps
spec:
  ports:
  - port: 8080
  selector:
    run: conference-app
  type: LoadBalancer
