apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: conference
  name: conference
spec:
  replicas: 3
  selector:
    matchLabels:
      run: conference
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: conference
    spec:
      containers:
      # - image: tkrausjr/conference-app
      - image: harbor.mbentley.net/tkraus/conference-app@sha256:f860bf8a63f7069a1f297716ae523ce6e158cc31ef64e449a34ade83316a9b8c
        imagePullPolicy: Always
        name: conference-app
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
