apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
 name: tanzu-cli-cc06
 namespace: env2-namespace
spec:
 clusterNetwork:
   pods:
     cidrBlocks:
     - 192.0.2.0/16
   serviceDomain: cluster.local
   services:
     cidrBlocks:
     - 198.51.100.0/12
 topology:
   class: tanzukubernetescluster
   controlPlane:
     metadata: {}
     replicas: 1
   variables:
   - name: storageClasses
     value:
     - nfs-k8s
       vsan-k8s
   - name: ntp
     value: time.vmware.com
   - name: vmClass
     value: best-effort-xsmall
   - name: storageClass
     value: nfs-k8s
   version: v1.22.11+vmware.2
   workers:
     machineDeployments:
     - class: node-pool
       metadata: {}
       name: np-2
       replicas: 1
