hub:
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  baseUrl: /
  cookieSecret:
  publicURL:
  initContainers: []
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  consecutiveFailureLimit: 5
  activeServerLimit:
  deploymentStrategy:
    ## type: Recreate
    ## - sqlite-pvc backed hubs require the Recreate deployment strategy as a
    ##   typical PVC storage can only be bound to one pod at the time.
    ## - JupyterHub isn't designed to support being run in parallell. More work
    ##   needs to be done in JupyterHub itself for a fully highly available (HA)
    ##   deployment of JupyterHub on k8s is to be possible.
    type: Recreate
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 3Gi
      subPath:
      storageClassName: pacific-gold-storage-policy
singleuser:
  image:
    name: jupyter/scipy-notebook
    tag: a95cb64dfe10
  memory:
    limit: 5G
    guarantee: 2G
  storage:
    type: dynamic
    dynamic:
      storageClass: pacific-gold-storage-policy
  lifecycleHooks:
    postStart:
      exec:
        command: ["/usr/bin/git", "clone", "https://github.com/tkrausjr/data-science-demos.git", "finance-analysis"]
proxy:
  secretToken: "c86a373144e4e8b1341fa5661cdc70f165856ba48eb54028eb844d41f1f2aeb4d4a0cca29b9548d52cb9b4c2fb901aa00537a9d37451a6f77953add34039ca56"

