apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: busybox
  name: broke-deploy
spec:
  replicas: 15
  selector:
    matchLabels:
      run: busybox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: busybox
    spec:
      containers:
      - name: ready
        image: harbor.tpmlab.vmware.com/proxy/library/busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 1; rm -rf /tmp/healthy; sleep 9000
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 1
          periodSeconds: 3
      restartPolicy: Always

