apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: busybox
  name: busy-broken-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: busybox
    spec:
      containers:
      - name: liveness
        image: harbor.tpmlab.vmware.com/proxy/library/busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 5; rm -rf /tmp/healthy; sleep 9000
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 2
          periodSeconds: 5
      restartPolicy: Always

