apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: conference
  name: conference
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      run: conference
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: conference
    spec:
      containers:
      - image: harbor.mbentley.net/tkraus/conference-app:v4
        imagePullPolicy: Always
        name: conference-app
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
