kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-claim
spec:
  storageClassName:   # Must put the field with no value and no single quotes to use the Default Storage Class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
