# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: springmusic
  name: springmusic
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: springmusic
  template:
    metadata:
      labels:
        run: springmusic
    spec:
      containers:
      - image: eoghank/springmusic:postgres1107
        name: springmusic
        #imagePullPolicy: Always
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://ahead-news-postgresql.default.svc.cluster.local:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
<<<<<<< HEAD
          value: "VMware1!"
=======
<<<<<<< HEAD
          value: "VMware1!"
=======
          value: "***REMOVED***"
>>>>>>> b285619d51741baf8ffe07cc4e6ec8ae55aace31
>>>>>>> 648105fe89e1d564c72cc84abc33c653ec876fca
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
