# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmusic
  labels:
    run: springmusic
    allowingress: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: springmusic
  template:
    metadata:
      labels:
        run: springmusic
    spec:
      containers:
      - image: eoghank/springmusic:postgres1107
        name: springmusic
        imagePullPolicy: IfNotPresent 
        #Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://ahead-news-postgresql:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
<<<<<<< HEAD
          value: "VMWare1!"
<<<<<<< HEAD
=======
=======
<<<<<<< HEAD
          value: "***REMOVED***"
>>>>>>> 648105fe89e1d564c72cc84abc33c653ec876fca
=======
          value: "changeme"
>>>>>>> 6adad2737d768715e248a97956f90aa0271230e0
>>>>>>> b285619d51741baf8ffe07cc4e6ec8ae55aace31
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
