# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: springmusic-runasroot
  name: springmusic-runasroot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: springmusic-runasroot
  template:
    metadata:
      labels:
        run: springmusic-runasroot
    spec:
      containers:
      - image: eoghank/springmusic:postgres1107
        name: springmusic-runasroot
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://ahead-news-postgresql:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
<<<<<<< HEAD
          value: "VMWare1!"
=======
          value: "***REMOVED***"
>>>>>>> b285619d51741baf8ffe07cc4e6ec8ae55aace31
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
