# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: springmusic
  name: springmusic
spec:
  replicas: 3
  selector:
    matchLabels:
      run: springmusic
  template:
    metadata:
      labels:
        run: springmusic
    spec:
      containers:
      - image: eoghank/springmusic:wavefront
        name: springmusic
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgrescreds
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgrescreds
              key: password
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://ahead-news-postgresql:5432/postgres"
        # - name: SPRING_DATASOURCE_USERNAME
        #  value: "postgres"
        # - name: SPRING_DATASOURCE_PASSWORD
<<<<<<< HEAD
        #  value: "VMWare1!"
=======
        #  value: "***REMOVED***"
>>>>>>> b285619d51741baf8ffe07cc4e6ec8ae55aace31
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
