apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: app-cluster
  namespace: spvn
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vsan-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 10Gi
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: np1
      replicas: 2
      vmClass: best-effort-medium
      storageClass: vsan-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 50Gi      
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
  settings:
    storage:
      classes: ["nfs-policy","vsan-policy"]      
      defaultClass: vsan-policy                     #Default PVC storage class
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["198.19.0.0/16"]
      services:
        cidrBlocks: ["198.51.100.0/24"]
