apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: infrastructure
  namespace: spvn
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: nfs-placement
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 10Gi
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: np1
      replicas: 2
      vmClass: best-effort-small
      storageClass: nfs-placement
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 25Gi      
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
  settings:
    storage:
      classes: ["vsan-placement"]      
      defaultClass: vsan-placement                   #Default PVC storage class
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["192.0.0.0/16"]
      services:
        cidrBlocks: ["198.51.100.0/24"]
