apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-sc-upgrade-v1-20-9
  namespace: fedex-grd
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: vsan-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 4Gi
      tkr:  
        reference:
          name: v1.20.9---vmware.1-tkg.1.a4cee5b
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-small
      storageClass: nfs-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 10Gi      
      tkr:  
        reference:
          name: v1.20.9---vmware.1-tkg.1.a4cee5b
  settings:
    storage:
      classes: ["nfs-policy"]      
      defaultClass: nfs-policy                     #Default PVC storage class
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["192.0.0.0/16"]
      services:
        cidrBlocks: ["198.51.100.0/24"]
