apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tap-1-kubectl
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.26.5+vmware.2-fips.1-tkg.1
    controlPlane:
      replicas: 1
      vmClass: tap-1-rightsize
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: np-1
          replicas: 3
          
          volumes:
            - name: containerd
              mountPath: /var/lib/containerd
              capacity:
                storage: 110Gi
    variables:
    - name: vmClass
      value: tap-1-rightsize
      # default storageclass for control plane and node pool
    - name: storageClass
      value: nfs-datastores

