apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tap-1-kubectl
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tkg-vsphere-default-v1.1.1
    version: v1.26.5+vmware.2-fips.1-tkg.1
    controlPlane:
      replicas: 1
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: np-1
          replicas: 1
    variables:
    - name: controlPlane
      value:
        machine:
          diskGiB: 110
          memoryMiB: 9164
          numCPUs: 6
    - name: worker
      value:
        machine:
          diskGiB: 110
          memoryMiB: 9164
          numCPUs: 6
      # default storageclass for control plane and node pool
    - name: storageClass
      value: nfs-k8s

