apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-02-3zones-defaultsc
spec:
  topology:
    controlPlane:
      tkr:
        reference:
          name: v1.23.8---vmware.2-tkg.1-zshippable
      replicas: 1
      vmClass: best-effort-small
      storageClass: local-datastores
    nodePools:
    - replicas: 1
      name: np-1
      failureDomain: zone-1
      vmClass: best-effort-small
      storageClass: local-datastores
    - replicas: 1
      name: np-2
      failureDomain: zone-2
      vmClass: best-effort-small
      storageClass: local-datastores
    - replicas: 1
      name: np-3
      failureDomain: zone-3
      vmClass: best-effort-small
      storageClass: local-datastores
  settings:
    storage:
      classes: ["local-datastores"]
      defaultClass: local-datastores
    network:
      cni:
        name: antrea
      services:
        cidrBlocks:
        - 198.51.100.0/12
      pods:
        cidrBlocks:
        - 192.0.2.0/16
      serviceDomain: cluster.local
