apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  namespace: test-ns-1
  name: k8s-129-03-test
  annotations:
    # this annotation is used to identify the cluster
    # in the tkg cluster list
    tkg.tanzu.vmware.com/cluster-name: k8s-129-03-test
    # this annotation is used to identify the cluster
    # in the tkg cluster list
    tkg.tanzu.vmware.com/cluster-type: workload
    deployedby: argocd
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.192.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.29.4---vmware.3-fips.1-tkg.1
    controlPlane:
      replicas: 1
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 2
    variables:
      - name: vmClass
        value: best-effort-medium
      # default storageclass for control plane and node pool
      - name: storageClass
        value: k8s-vsan
      - name: defaultStorageClass
        value: k8s-vsan