apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lvdc-env1-sort
  namespace: sort
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.192.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.28.8---vmware.1-fips.1-tkg.2
    controlPlane:
      replicas: 1
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 3
    variables:
      - name: vmClass
        value: best-effort-large
      # default storageclass for control plane and node pool
      - name: storageClass
        value: k8s-vsan
      - name: defaultStorageClass
        value: k8s-vsan


