apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: tanzucli-02
spec:
  topology:
    controlPlane:
      tkr:
        reference:
          name: v1.23.8---vmware.2-tkg.1-zshippable
      replicas: 1
      vmClass: best-effort-small
      storageClass: nfs-k8s
    nodePools:
    - replicas: 1
      name: np-1
      vmClass: best-effort-small
      storageClass: nfs-k8s
  settings:
    storage:
      classes: ["nfs-k8s"]
      defaultClass: nfs-k8s
    network:
      cni:
        name: antrea
      services:
        cidrBlocks:
        - 198.51.100.0/12
      pods:
        cidrBlocks:
        - 192.0.2.0/16
      serviceDomain: cluster.local
