apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tmc-local-a       
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.24.9+vmware.1-tkg.4
    controlPlane:
      replicas: 1
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: np1
          replicas: 1
    variables:
      - name: vmClass
        value: best-effort-large
      # default storageclass for control plane and node pool
      - name: storageClass
        value: nfs-datastores
      - name: defaultStorageClass
        value: nfs-datastores
