apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  namespace: tpk8s-build-run
  name: build-02
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.192.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.29.4---vmware.3-fips.1-tkg.1
    controlPlane:
      replicas: 1
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 2
    variables:
      - name: vmClass
        value: build-02
      # default storageclass for control plane and node pool
      - name: storageClass
        value: k8s-tpk8s-01-cluster
      - name: defaultStorageClass
        value: k8s-tpk8s-01-cluster
      - name: nodePoolVolumes
        value:
          #name of the PVC to be used as the suffix (node.name)
          - name: node-pool-vol1
            #mountPath is the directory where the volume device is mounted
            #takes the form /dir/path
            mountPath: /var/lib/containerd
            #storageClass is the storage class to use for the PVC
            storageClass: k8s-tpk8s-01-cluster
            #capacity is the PVC storage capacity
            capacity:
              #storage sets the capacity for the disk volume
              #if not specified defaults to storageClass capacity
              storage: 40Gi 


