apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: wkld02-zones
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.24.9+vmware.1-tkg.4
    controlPlane:
      replicas: 1
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          failureDomain: zone-1
          name: np1
          replicas: 1
        - class: node-pool
          failureDomain: zone-2
          name: np2
          replicas: 1
        - class: node-pool
          failureDomain: zone-3
          name: np3
          replicas: 1
    variables:
      - name: vmClass
        value: best-effort-small
      # default storageclass for control plane and node pool
      - name: storageClass
        value: tkgs-az-local

