apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: wkld02-small
  namespace: test1-nsx-vpc
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.192.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.31.4---vmware.1-fips-vkr.3
    controlPlane:
      replicas: 3
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: compute
          replicas: 2
          variables:
            overrides:
            - name: vmClass
              value: tmc-sm-rightsize
    variables:
      # Default VMClass and will always use for CP Nodes. You can override the machineDeployments
      # VMClass
      - name: vmClass
        value: best-effort-xsmall
      # default storageclass for control plane and node pool
      - name: storageClass
        value: vsan-default-storage-policy
      - name: defaultStorageClass
        value: vsan-default-storage-policy

              


