apiVersion: v1
kind: Service
metadata:
  labels:
    app: hackazon-deployment
  name: hackazon-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hackazon-deployment
  type: NodePort
