apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackazon-ingress
spec:
  rules:
  - host: hackazon.tpmlab.vmware.com
    http:
      paths:
      - backend:
          service:
            name: hackazon-deployment
            port:
              number: 80
        path: /
        pathType: Prefix
