# gangway k14s objects managed by kapp-controller
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gangway
  namespace: tanzu-system-auth
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  syncPeriod: 5m
  serviceAccountName: gangway-extension-sa
  fetch:
    - image:
        url: projects.registry.vmware.com/tkg/tkg-extensions-templates:v1.3.1_vmware.1
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - tkg-extensions/common
          - tkg-extensions/authentication/gangway
        inline:
          pathsFrom:
            - secretRef:
                name: gangway-data-values
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]
