apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: vks-cluster-replica-test
#namespace: shared-svcs-hgybt
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: builtin-generic-v3.7.0
      namespace: vmware-system-vks-public
    version: v1.36.1---vmware.4-vkr.5
    variables:
      - name: vmClass
        value: best-effort-xsmall
      - name: storageClass
        value: vsan-default-storage-policy
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-e80e0171710ad97e3
    workers:
      machineDeployments:
        - class: node-pool
          name: vks-cluster-replica-test-np-kz46
          replicas: 3
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-e80e0171710ad97e3
