kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-slave-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 
  resources:
    requests:
      storage: 2Gi
