apiVersion: v1
kind: Pod
metadata:
  name: pod-env-vars
spec:
  containers:
    - name: configmap-logging-cntr
      image: harbor.tpmlab.vmware.com/library/busybox
      command: [ "/bin/sh", "-c", "env" ]

  restartPolicy: Never