apiVersion: v1
kind: Pod
metadata:
  name: configmap-logging-pod
spec:
  containers:
    - name: configmap-logging-cntr
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "echo Error Level is: $(LOG_LEVEL) - Error Location is: $(LOG_LOCATION)" ]
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.level
        - name: LOG_LOCATION
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.location
  restartPolicy: Never