kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-slave-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pacific-gold-storage-policy
  resources:
    requests:
      storage: 2Gi
