kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: projectpacific-storage-policy
  resources:
    requests:
      storage: 2Gi
