apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: large-k8s6 # name of cluster
  namespace: fourth
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium # vmclass to be used for master(s)
      storageClass: projectpacific-storage-policy
    workers:
      count: 5
      class: best-effort-large # vmclass to be used for workers(s)
      storageClass: projectpacific-storage-policy
  distribution:
    version: v1.16.8       # Removed all before the v - photon-3-k8s-v1.16.8---vmware.1-tkg.1.6b5edc7
