apiVersion: run.tanzu.vmware.com/v1alpha1               #TKG API endpoint
kind: TanzuKubernetesCluster                            #required parameter
metadata:
  name: cl1                           #cluster name, user defined 
spec:
  distribution:
    version: v1.19                                      #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                          #number of control plane nodes
      class: best-effort-small                     #vmclass for control plane nodes
      storageClass: default-sc        #storageclass for control plane
    workers:
      count: 3                                        #number of worker nodes
      class: best-effort-medium                       #vmclass for worker nodes
      storageClass: default-sc        #storageclass for worker nodes
  settings:
    storage:
      defaultClass: default-sc                     #Default PVC storage class
    network:
 #    cni:                                      #Uncomment for Calico.  Antrea is default as of 1.17
 #      name: calico                            #Uncomment for Calico.  Antrea is default as of 1.17
      services:
        cidrBlocks: ["198.51.100.0/12"]          #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/16"]             #Cannot overlap with Supervisor Cluster
