apiVersion: run.tanzu.vmware.com/v1alpha1               #TKG API endpoint
kind: TanzuKubernetesCluster                            #required parameter
metadata:
  name: tkg-cluster-1                            #cluster name, user defined 
spec:
  distribution:
    version: v1.18                                      #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                          #number of control plane nodes
      class: best-effort-medium                     #vmclass for control plane nodes
      storageClass: default-sc        #storageclass for control plane
    workers:
      count: 1                                        #number of worker nodes
      class: best-effort-medium                       #vmclass for worker nodes
      storageClass: default-sc        #storageclass for worker nodes
  settings:
    storage:
      defaultClass: default-sc                     #Default PVC storage class
