apiVersion: run.tanzu.vmware.com/v1alpha1               #TKG API endpoint
kind: TanzuKubernetesCluster                            #required parameter
metadata:
  name: tkg-gc-calico                           #cluster name, user defined 
  namespace: first                                  #supervisor namespace
spec:
  distribution:
    version: v1.18                                      #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                          #number of control plane nodes
      class: best-effort-medium                      #vmclass for control plane nodes
      storageClass: gold-policy         #storageclass for control plane
    workers:
      count: 2                                        #number of worker nodes
      class: best-effort-medium                        #vmclass for worker nodes
      storageClass: gold-policy         #storageclass for worker nodes
  settings:
    storage:
      defaultClass: silver-policy                     #Default PVC storage class
    network:
      cni:
        name: calico
      pods:
        cidrBlocks:
        - 193.0.2.0/16
      serviceDomain: managedcluster.local
      services:
        cidrBlocks:
        - 195.51.100.0/12
