enable_ansible_debug: true # set value to true for verbose output from ansible
nsx_t_pipeline_branch: test_ovftool

# format: "http://<jumphost_ip>:40001"
nsx_image_webserver: "http://110.371.13.90:40001"
ova_file_name: "nsx-unified-appliance-2.3.0.0.0.10085405.ova" #Uncomment this if downloaded file manually and placed under /home/concourse
ovftool_file_name: "VMware-ovftool-4.3.0-10104578-lin.x86_64.bundle"   #Uncomment this if downloaded file manually and placed under /home/concourse

# vCenter to deploy the NSX manager
vcenter_ip: 110.371.13.81
vcenter_username: administrator@vsphere.local
vcenter_password: "*******"
vcenter_datacenter: Datacenter
vcenter_cluster: Nested-PKS
vcenter_datastore: nfs-ubuntu-01

# NSX manager general network settings
mgmt_portgroup: 'VM 1525'
dns_server: 110.371.13.90
dns_domain: tpmlab.vmware.com
ntp_servers: 110.371.13.90
default_gateway: 110.371.13.90
netmask: 255.255.255.0

nsx_manager_ip: 110.371.13.82
nsx_manager_username: admin
nsx_manager_password: *******
nsx_manager_assigned_hostname: "nsxt-mgr-23" # this hostname+dns_domain will be FQDN
nsx_manager_root_pwd: *******    # Min 8 chars, upper, lower, number, special digit
nsx_manager_deployment_size: small   # Recommended for real barebones demo, smallest setup
nsx_manager_ssh_enabled: true
resource_reservation_off: true

# Compute manager credentials should be the same as above vCenter's if
# controllers and edges are to be on the same vCenter
compute_manager_username: "administrator@vsphere.local"
compute_manager_password: "*******"
# compute manager for the compute cluster (2nd vCenter)
compute_manager_2_vcenter_ip: 
compute_manager_2_username: 
compute_manager_2_password: 

edge_uplink_profile_vlan: 0 # For outbound uplink connection used by Edge, usually keep as 0
esxi_uplink_profile_vlan: 0 # For internal overlay connection used by Esxi hosts, usually trasnport VLAN ID

# Virtual Tunnel Endpoint network ip pool
vtep_ip_pool_cidr: 10.33.33.0/27
vtep_ip_pool_gateway: 10.33.33.1
vtep_ip_pool_start: 10.33.33.10
vtep_ip_pool_end: 10.33.33.16

# Tier 0 router
tier0_router_name: PKS-T0
tier0_uplink_port_ip: 192.168.40.5
tier0_uplink_port_subnet: 24
tier0_uplink_next_hop_ip: 192.168.40.1
tier0_uplink_port_ip_2: 192.168.40.6
tier0_ha_vip: 192.168.40.3

## Controllers
controller_ips: 110.371.13.83 #comma separated based on number of required controllers
controller_default_gateway: 110.371.13.90
controller_ip_prefix_length: 24
controller_hostname_prefix: controller # Generated hostname: controller_1.corp.local.io
controller_cli_password: "*******" # Min 8 chars, upper, lower, num, special char
controller_root_password: "*******"
controller_deployment_size: "SMALL"
vc_datacenter_for_controller: Datacenter
vc_cluster_for_controller: Nested-PKS
vc_datastore_for_controller: nfs-ubuntu-01
vc_management_network_for_controller: "VM 1525"
controller_shared_secret: "**************"

## Edge nodes
edge_ips: 110.371.13.40,110.371.13.85    #comma separated based in number of required edges
edge_default_gateway: 110.371.13.90
edge_ip_prefix_length: 24
edge_hostname_prefix: nsx-t-edge
edge_transport_node_prefix: edge-transp-node
edge_cli_password: "*******"
edge_root_password: "*******"
edge_deployment_size: "large" #Large recommended for PKS deployments
vc_datacenter_for_edge: Datacenter
vc_cluster_for_edge: Nested-PKS
vc_datastore_for_edge: nfs-ubuntu-01
vc_uplink_network_for_edge: "Edges_Uplink"
vc_overlay_network_for_edge: "Geneve 3333 Edges"
vc_management_network_for_edge: "VM 1525"

## ESX hosts
#Intsll vSphere clusters automatically
clusters_to_install_nsx: Nested-PKS    #Comma seprated
per_cluster_vlans: 0  #Comma seprated, order of VLANs applied same as order of clusters

esx_ips: "" # additional esx hosts, if any, to be individually installed
esx_os_version: "6.5.0"
esx_root_password: "ca$hc0w"
esx_hostname_prefix: "esx-host"

esx_available_vmnic: "vmnic1" # comma separated physical NICs, applies to both cluster installation or ESXi installation

nsx_t_t1router_logical_switches_spec: |
  t1_routers:
  # Add additional T1 Routers or collapse switches into same T1 Router as needed
  - name: T1-Router-PKS-Mgmt
    switches:
    - name: PKS-Mgmt
      logical_switch_gw: 10.31.0.1 # Last octet should be 1 rather than 0
      subnet_mask: 24

nsx_t_container_ip_block_spec: |
  container_ip_blocks:
  - name: PKS-node-ip-block
    cidr: 10.41.0.0/16

  - name: PKS-pod-ip-block
    cidr: 172.16.0.0/16


nsx_t_external_ip_pool_spec: |
  external_ip_pools:

  - name: snat-vip-pool-for-pks
    cidr: 10.51.0.0/24
    start: 10.51.0.10 # Should not include gateway
    end: 10.51.0.200  # Should not include gateway

  - name: tep-ip-pool2
    cidr: 10.33.33.0/27
    start: 10.33.33.2
    end: 10.33.33.12


nsx_t_nat_rules_spec: |
  nat_rules:
  # Sample entry for  PKS-Infra network
  - t0_router: PKS-T0
    nat_type: snat
    source_network: 10.31.0.0/24      # PKS Infra network cidr
    translated_network: 192.168.40.31      # SNAT External Address for PKS networks
    rule_priority: 8001                  # Lower priority

  # Sample entry for PKS-Services network
  - t0_router: PKS-T0
    nat_type: snat
    source_network: 10.41.0.0/24      # PKS Clusters network cidr
    translated_network: 192.168.40.41     # SNAT External Address for PKS networks
    rule_priority: 8001                  # Lower priority

  # Sample entry for allowing inbound to PKS Ops manager
  - t0_router: PKS-T0
    nat_type: dnat
    destination_network: 192.168.40.2     # External IP address for PKS opsmanager
    translated_network: 10.31.0.2    # Internal IP of PKS Ops manager
    rule_priority: 1024                  # Higher priority

  # Sample entry for allowing inbound to PKS Controller
  - t0_router: PKS-T0
    nat_type: dnat
    destination_network: 192.168.40.4     # External IP address for PKS controller
    translated_network: 10.31.0.4     # Internal IP of PKS Controller
    rule_priority: 1024                  # Higher priority

  # Sample entry for allowing outbound from PKS Controller to external
  - t0_router: PKS-T0
    nat_type: dnat
    destination_network: 192.168.40.5       # Internal IP of PKS controller
    translated_network: 10.31.0.5      # External IP address for PKS controller
    rule_priority: 1024                  # Higher priority


nsx_t_csr_request_spec: |
  csr_request:
    #common_name not required - would use nsx_t_manager_host_name
    org_name: Company            # EDIT
    org_unit: net-integ          # EDIT
    country: US                  # EDIT
    state: CA                    # EDIT
    city: SF                     # EDIT
    key_size: 2048               # Valid values: 2048 or 3072
    algorithm: RSA               # Valid values: RSA or DSA


nsx_t_lbr_spec: |
  loadbalancers:

nsx_t_ha_switching_profile_spec: | 
ha_switching_profiles: 
