apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  capacity:
    storage: 6Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle 
  nfs: 
    path: /var/nfsexport
    server: 10.193.245.101
    readOnly: false
