kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-slave-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "vsphere-spbm-vsan-k8s-sc" 
  resources:
    requests:
      storage: 2Gi
