apiVersion: v1
kind: Service
metadata:
  labels:
    run: conference-app
  name: conference-app
  namespace: my-namespace
spec:
  ports:
  - port: 8080
  selector:
    run: conference-app
  type: LoadBalancer
