#@data/values
#@overlay/match-child-defaults missing_ok=True
---
monitoring:
  grafana:
    image:
      repository: "projects.registry.vmware.com/tkg/grafana"
    secret:
      admin_password: "Vk13YXJlMSE="
    service:
      type: "LoadBalancer"
    ingress:
      enabled: false    # Had to do this because somewhere it defaults to Ingress True
  grafana_init_container:
    image:
      repository: "projects.registry.vmware.com/tkg/grafana"
  grafana_sc_dashboard:
    image:
      repository: "projects.registry.vmware.com/tkg/grafana"
