apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: alana-pod-secret-docker
    image: harbor.tpmlab.vmware.com/library/nginx:latest
  imagePullSecrets:
  - name: regsecret

