apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      containers:
      - name: wavefront-proxy
        image: harbor.tpmlab.vmware.com/library/wavefront-proxy-squid:latest 
        imagePullPolicy: Always
        env:
        - name: WAVEFRONT_URL
          value: https://longboard.wavefront.com/api/
        - name: WAVEFRONT_TOKEN
<<<<<<< HEAD
          value: 18574d35-7e20-4153-b0e9-9afaec6abffa
=======
          value: <>
>>>>>>> ece5f9ae12717009eecde6650d5502ae021ebf06
        ports:
        - containerPort: 2878
          protocol: TCP
        - containerPort: 4242
          protocol: TCP
        securityContext:
          privileged: false

