apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gb-rewrite
spec:
  routes:
  - conditions:
    - prefix: /guestbook
    pathRewritePolicy:
      replacePrefix:
      - prefix: /guestbook
        replacement: /
    services:
    - name: gb-frontend
      port: 80
  virtualhost:
    fqdn: gb.tpmlab.vmware.com

