kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-slave-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: space-efficient
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
