#@data/values
#@overlay/match-child-defaults missing_ok=True
---
logging:
  image:
    repository: projects.registry.vmware.com/tkg
tkg:
  instance_name: "vsphere-tpmlab"
  cluster_name: "tkg-cluster-1"
fluent_bit:
  output_plugin: "syslog"
  syslog:
    host: "10.173.13.83"
    port: "514"
    mode: "UDP"
    format: "rfc5424"


