apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-practice
  name: pod-practice
spec:         # This is the POD Spec
  serviceAccountName: pod-practice-sa  # K8s API Token mounted in containers /var/run/secrets/kuernetes.io/serviceaccount/
  volumes:
    - name: pvc-pod-practice
      persistentVolumeClaim:        # If your SC doesnt support dynamic provisioning you need to apply pv-lesson-pv.yaml
        claimName: vsan-wkld-pvc    # Assumes you applied pv-lesson-pvc.yaml to creat the PVC
    - name: user-configmap-vol
      configMap:          # Crete a volume from a configmap
        name: users       # name of configMap to mount as volume
    - name: passwords-secret-vol
      secret:                   # Crete a volume from a secret
        secretName: passwords   # name of secret to mount as volume
  initContainers:
  - name: pod-init
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox:1.28
    # Init container keeps looping until a SVC named 'myservice' exists in same namespace as this POD. (default) 
    command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
  containers:
  - image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/nginx:alpine
    name: pod-practice
    resources:
      requests:
        cpu: "64m"
        memory: "32Mi"
    env:
      - name: USER_1    # Define the environment variable
        valueFrom:
          configMapKeyRef:    # Use a ConfigMap 
            name: users       # Name of ConfigMap 
            key: user1        # Name of Key in ConfigMap
      - name: TOM_PASSWORD    # Define the environment variable
        valueFrom:
          secretKeyRef:       # Use a Secret 
            name: passwords   # Name of Secret 
            key: tom          # Name of Key in Secret
    volumeMounts:
      - name: pvc-pod-practice              # Name of PVC Volume from above .
        mountPath: /tmp/pvc-volume          # Will create the directory for us. Keys listed under this directory      
      - name: user-configmap-vol            # Name of Volume from above in spec.
        mountPath: /tmp/mnt-doesnotexist    # Will create the directory for us. Keys listed under this directory
      - name: passwords-secret-vol          # Name of Volume from above in spec.
        mountPath: /tmp/secret-passwords    # Will create the directory for us. Keys listed under this directory
  dnsPolicy: ClusterFirst
  restartPolicy: Always

