apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsan-wkld-pvc
spec:
  storageClassName: vsan-wkld-cluster # use hostpath for Docker Desktop or Minikube usually 'manual'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
