apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-deploy
  name: nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx-deploy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx-deploy
    spec:
      containers:
      - image: nginxdemos/hello
        imagePullPolicy: Always
        name: nginx-demo
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: nginx-svc
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    run: nginx-deploy
  sessionAffinity: None
  type: NodePort


